### ISSUE TITLE
Sort out serialization of large models on MacOS and Windows

### ISSUE THREAD

**Issue by alanakbik** [zalandoresearch/flair#174]
We have been getting a number of reports that serialization of very large models does not work on Mac OS (#171 #23) and Windows (#172) setups. It seems that this is a problem caused by the pickle module which we use for serialization. 

To reproduce the error on Windows / Mac OS, do 

```python
from flair.models import SequenceTagger
tagger = SequenceTagger.load('ner-ontonotes-fast')
```

To fix this we need to either: 
- Figure out what we must do so that pickling of very large objects (>1GB) works across platforms
- Find an alternative to serialization with pickle 

Fixing this issue is a priority for us - any help from the community with mac OS / Windows setups is appreciated!

**Comment by rohitmujumdar** [comment]
Hi Alan,
I would be glad to help with the testing of flair for Windows.

**Comment by devmaha** [comment]
Is there a tentative date by when this issue would get fixed. For testing on Mac, I can help.

**Comment by alanakbik** [comment]
Thanks - I'm hoping we'll have this fixed at the beginning of next week and then perhaps do another release (0.3.2) at the end of next week!

**Comment by alanakbik** [comment]
I've checked in a workaround to address the problem. Positive side effects are that word embeddings and some trained models are now smaller, so faster to store / load. Also, I've added FastText embeddings for 9 languages in smaller size ('de', 'pl', 'fr', 'it', 'es', 'pt', 'nl', 'ar', 'sv'). 

This branch now lets me use the 'ner-ontonotes' model and can train large models on my MacOS setup. 

@devmaha @rohitmujumdar - could you test this branch on your respective setups?

**Comment by devmaha** [comment]
@alanakbik Thank you for quick turnaround. Could you please point me to the path of this model on aws.
The one here - https://s3.eu-central-1.amazonaws.com/alan-nlp/resources/models-v0.2/NER-ontoner--h256-l1-b32-%2Bcrawl%2Bnews-forward-fast%2Bnews-backward-fast--v0.2/en-ner-ontonotes-fast-v0.2.pt I believe is old model (and is thus still failing).

**Comment by devmaha** [comment]
@alanakbik thanks for quick turnaround. I am on it. Will let you know how it goes

**Comment by devmaha** [comment]
Tested on windows - new model loads faster and works well. I was wondering what those 12 classes are that the model can identify. We could just see only a few.
